### ISSUE TITLE
Add line-wrapping for `.gpu-name`

### ISSUE THREAD

**Issue by kuenway** [Yuan-Yu/GPUDashboard#2]
The relevant CSS is in [`index.css`](https://github.com/kuenway/GPUDashboard/blob/master/fontEnd/index.css#L120)
Currently:
```css
.gpu-name {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 18px;
  font-weight: bold;
  margin-top: 10px;
  margin-bottom: 6px;
}
```
Suggested update:
```css
.gpu-name {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 18px;
  font-weight: bold;
  margin-top: 10px;
  margin-bottom: 6px;
  word-wrap: break-word;
  white-space: normal;
  max-width: 180px;
}
```

Or just modify [ViewStatus.html](https://github.com/kuenway/GPUDashboard/blob/master/ViewStatus.html#L16)
From:
```html
.gpu-name{font-family:Arial, Helvetica, sans-serif;font-size:18px;font-weight:bold;margin-top:10px;margin-bottom:6px}
```
To:
```html
.gpu-name{font-family:Arial, Helvetica, sans-serif;font-size:18px;font-weight:bold;margin-top:10px;margin-bottom:6px;word-wrap:break-word;white-space:normal;max-width:180px;}
```
